; generated by goldly on 2021-07-06 03:52:55
(ns goldly-bindings-generated
  (:require [clojure.walk]
            [goldly.service.core]
            [goldly.sci.lazy]
            [ui.code.goldly.core]
            [ui.markdown.goldly.core]
            [pinkgorilla.repl.cljs.core]
            [ui.site.template]
            [ui.site.ipsum]
            [ui.site.layout]))
(def bindings-generated
  {'parse-float pinkgorilla.repl.cljs.js/parse-float,
   'error pinkgorilla.repl.cljs.log/error,
   'register-tag pinkgorilla.repl.cljs.pinkie/register-tag,
   'println println,
   'timeout pinkgorilla.repl.cljs.js/timeout,
   'run-a goldly.service.core/run-a,
   'prosemirror ui.markdown.goldly.prosemirror-atom/prosemirror-atom,
   'error-boundary pinkie.error/error-boundary,
   'pinkie-render pinkie.pinkie-render/pinkie-render,
   'interval pinkgorilla.repl.cljs.js/interval,
   'set-system-state pinkgorilla.repl.cljs.goldly/set-system-state,
   'format goog.string/format,
   'sin pinkgorilla.repl.cljs.js/sin,
   'get-edn pinkgorilla.repl.cljs.http/get-edn,
   'app-db pinkgorilla.repl.cljs.reframe/app-db,
   'warn pinkgorilla.repl.cljs.log/warn,
   'get-str pinkgorilla.repl.cljs.http/get-str,
   'clipboard-set pinkgorilla.repl.clipboard/clipboard-set,
   'notify pinkgorilla.repl.cljs.webly/notify,
   'code ui.code.highlight.viewer/code-viewer,
   'dialog pinkgorilla.repl.cljs.webly/dialog,
   'codemirror ui.code.goldly.codemirror-atom/codemirror-atom,
   'text pinkie.text/text,
   'current-route pinkgorilla.repl.cljs.webly/current-route,
   'evt-val pinkgorilla.repl.cljs.js/evt-val,
   'clipboard-pop pinkgorilla.repl.clipboard/clipboard-pop,
   'reagent-page webly.web.handler/reagent-page,
   'run goldly.service.core/run,
   'alert pinkgorilla.repl.cljs.js/alert,
   'markdown ui.markdown.viewer/markdown-viewer,
   'lazytest goldly.sci.lazy/lazytest,
   'get-json pinkgorilla.repl.cljs.http/get-json,
   'info pinkgorilla.repl.cljs.log/info,
   'nav pinkgorilla.repl.cljs.webly/nav})
(def ns-generated
  {'walk {'postwalk clojure.walk/postwalk,
          'prewalk clojure.walk/prewalk,
          'keywordize-keys clojure.walk/keywordize-keys,
          'walk clojure.walk/walk,
          'postwalk-replace clojure.walk/postwalk-replace,
          'prewalk-replace clojure.walk/prewalk-replace,
          'stringify-keys clojure.walk/stringify-keys},
   'r {'atom reagent.core/atom},
   'rf {'dispatch re-frame.core/dispatch,
        'subscribe re-frame.core/subscribe},
   'site {'people ui.site.template/people,
          'message-button ui.site.template/message-button,
          'ipsum ui.site.ipsum/ipsum,
          'bullet-points ui.site.template/bullet-points,
          'main-with-header ui.site.layout/main-with-header,
          'foto-right ui.site.template/foto-right,
          'fotos-with-text ui.site.template/fotos-with-text,
          'foto-left ui.site.template/foto-left,
          'foto-bottom ui.site.template/foto-bottom,
          'sidebar-layout ui.site.layout/sidebar-layout}})
